### ISSUE TITLE
Unzip mess up with sub-folders

### ISSUE THREAD

**Issue by rochapablo** [sridharrajs/folder-zip#1]
Hey, I'm not sure why but when I unzip the file it create every sub-folder as parent ones. For example:

```
- file.zip
-- src
--- controllers
---- client
--- views
```

But when I unzip, I got

```
- src
-- src_controllers
-- src_controllers_client
-- src_views
```

Any idea?

**Comment by sridharrajs** [comment]
Testing with the folder structure you've provided, seem to work for me. Is it resolved?

**Comment by rochapablo** [comment]
Yes it was. Thank you.
